version: '3'
services:
  ares-api-huobi:
    image: huobiaggregate:last
    container_name: ares-api-huobi
    ports:
      - "8080:8080"
    environment:
      - BOOT_OPTIONS="--spring.redis.host=11.11.11.12"
    networks:
      hx_net:
        ipv4_address: 11.11.11.11
  ares-api-okex:
    image: okexaggregate:last
    container_name: ares-api-okex
    environment:
      - BOOT_OPTIONS="--spring.redis.host=11.11.11.12"
    networks:
      hx_net:
        ipv4_address: 11.11.11.13  
  redis:
    image: redis:latest
    container_name: compose-redis
    expose:
      - 6379
    ports:
      - "6379:6379"
    networks:
      hx_net:
        ipv4_address: 11.11.11.12

networks:
  hx_net:
    driver: bridge
    ipam:
      config:
        - subnet: 11.11.11.0/16    